stages:
  - deploy

deploy composer package:
  stage: deploy
  when: always
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  except:
    - branches
  before_script:
    - apt update -y
    - apt install -y curl
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://gitlab.virtuosereality.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'

generate documentation:
  stage: deploy
  when: always
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - doc
    expire_in: 10 years
  before_script:
    - apt update -y
    - apt install -y wget
    - wget http://phpdox.de/releases/phpdox.phar
    - chmod +x phpdox.phar
  script:
    - ./phpdox.phar
    - mv documentation/html/ doc/
