stages:
  - deploy

deploy composer package:
  stage: deploy
  when: always
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  except:
    - branches
  before_script:
    - apt update -y
    - apt install -y curl
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://gitlab.virtuosereality.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'

pages:
  stage: deploy
  when: manual
  artifacts:
    paths:
      - public
  before_script:
    - apt update -y
    - apt-get -y install apt-transport-https lsb-release ca-certificates curl
    - curl -sSL -o /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    - sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
    - apt update -y
    - apt install -y php7.3 php7.3-xml php7.3-mbstring php7.3-json php7.3-common
    - apt install -y wget
    - wget http://phpdox.de/releases/phpdox.phar
    - chmod +x phpdox.phar
  script:
    - ./phpdox.phar
    - mkdir .public
    - cp -r documentation/html/* .public
    - mv .public public
