stages:
  - deploy

deploy:
  stage: deploy
  when: always
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  except:
    - branches
  script:
    - apt update -y
    - apt install -y curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://gitlab.virtuosereality.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
